spring:
  main:
    banner-mode: "off"
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:classdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        use_sql_comments: true
        format_sql: true
logging:
  level:
    org:
      springframework:
        security: info
#        jdbc:
#          core:
#            JdbcTemplate: DEBUG
#            StatementCreatorUtils: TRACE
#      hibernate:
#        type:
#          descriptor:
#            sql: trace
