create table genero (
  id     bigint generated by default as identity,
  nombre varchar(255) not null,
  primary key (id)
);
create table pelicula (
  id              bigint generated by default as identity,
  director        varchar(255) not null,
  titulo          varchar(255) not null,
  fecha_estreno   date not null,
  poster          varchar(255) not null,
  genero_id       bigint,
  primary key (id)
);
create table rol (
  id          bigint       not null,
  descripcion varchar(255) not null,
  nombre      varchar(255) not null,
  primary key (id)
);
create table usuario (
  id       bigint generated by default as identity,
  login    varchar(255)      not null,
  password varchar(255)      not null,
  enabled  bool default true not null,
  primary key (id)
);
create table usuario_roles (
  usuario_id bigint not null,
  roles_id   bigint not null,
  primary key (usuario_id, roles_id)
);
alter table pelicula
  add constraint FKgy0vpfv1vyewg7xv19h8d8ado
foreign key (genero_id)
references genero;
alter table usuario_roles
  add constraint FK861wr18rjyh6pmadvor1u36vb
foreign key (roles_id)
references rol;
alter table usuario_roles
  add constraint FKqblnumndby0ftm4c7sg6uso6p
foreign key (usuario_id)
references usuario;
