create table sala
(
    id                      bigint generated by default as identity,
    nombre                  varchar(255) not null,
    responsable             varchar(255) not null,
    fecha_de_reserva        timestamp    not null,
    tiempo_reserva_en_horas int          not null,
    icono                   varchar(255) not null,
    primary key (id)
);
create table rol
(
    id          bigint       not null,
    descripcion varchar(255) not null,
    nombre      varchar(255) not null,
    primary key (id)
);
create table usuario
(
    id       bigint generated by default as identity,
    login    varchar(255)      not null,
    password varchar(255)      not null,
    enabled  bool default true not null,
    primary key (id)
);
create table usuario_roles
(
    usuario_id bigint not null,
    roles_id   bigint not null,
    primary key (usuario_id, roles_id)
);
alter table usuario_roles
    add constraint FK861wr18rjyh6pmadvor1u36vb
        foreign key (roles_id)
            references rol;
alter table usuario_roles
    add constraint FKqblnumndby0ftm4c7sg6uso6p
        foreign key (usuario_id)
            references usuario;
